CREATE DATABASE IF NOT EXISTS proyecto;
use proyecto;

CREATE TABLE IF NOT EXISTS blog (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tit VARCHAR(100) NOT NULL,
    news VARCHAR(250) NOT NULL,
    img VARCHAR(100)
    );


CREATE TABLE IF NOT EXISTS users (
    user VARCHAR(100) NOT NULL PRIMARY KEY,
    pass VARCHAR(250) NOT NULL
);
INSERT INTO users VALUES ('admin', 'admin');
INSERT INTO users VALUES ('sasa', 'sasa'); 

